"""Catalog metadata for SwiftProPDF web tools."""

TOOLS = [
    {
        "path": "unlock",
        "title": "Unlock PDF",
        "icon_html": "🔓",
        "description": "Remove password protection from your PDF in seconds.",
        "post_route": "unlock",
        "input_label": "Locked PDF",
        "input_name": "pdf",
        "accept": "application/pdf,.pdf",
        "multiple": False,
        "action_label": "Unlock PDF",
        "fields": [
            {"type": "password", "name": "password", "label": "Password", "placeholder": "Enter PDF password", "required": False},
        ],
        "related": ["compress", "split", "merge"],
        "tips": ["Keep your password ready.", "Only PDF files are accepted.", "Download starts automatically."],
    },
    {
        "path": "lock",
        "title": "Lock PDF",
        "icon_html": "🔒",
        "description": "Add password protection to a PDF before sharing.",
        "post_route": "lock",
        "input_label": "PDF file",
        "input_name": "pdf",
        "accept": "application/pdf,.pdf",
        "multiple": False,
        "action_label": "Lock PDF",
        "fields": [
            {"type": "password", "name": "password", "label": "Password", "placeholder": "Create a PDF password", "required": True},
        ],
        "related": ["unlock", "compress", "merge"],
        "tips": ["Use a strong password.", "Keep a copy of the password safely.", "Encrypted PDFs must be unlocked before editing."],
    },
    {
        "path": "split",
        "title": "Split PDF",
        "icon_html": "✂️",
        "description": "Extract selected pages from a PDF into a new file.",
        "post_route": "split",
        "input_label": "PDF file",
        "input_name": "pdf",
        "accept": "application/pdf,.pdf",
        "multiple": False,
        "action_label": "Split PDF",
        "fields": [
            {"type": "text", "name": "page_ranges", "label": "Pages to extract", "placeholder": "Example: 1-3,5", "required": True},
        ],
        "related": ["merge", "compress", "delete-pages"],
        "tips": ["Use commas for separate pages.", "Use a dash for ranges.", "Leave blank for full export."],
    },
    {
        "path": "merge",
        "title": "Merge PDF",
        "icon_html": "📚",
        "description": "Combine multiple PDF files into one document.",
        "post_route": "merge",
        "input_label": "PDF files",
        "input_name": "pdfs",
        "accept": "application/pdf,.pdf",
        "multiple": True,
        "action_label": "Merge PDFs",
        "fields": [],
        "related": ["split", "compress", "delete-pages"],
        "tips": ["Upload files in the order you want them merged.", "Use at least two PDFs.", "The result downloads automatically."],
    },
    {
        "path": "compress",
        "title": "Compress PDF",
        "icon_html": "🗜️",
        "description": "Reduce PDF size for faster sharing and storage.",
        "post_route": "compress",
        "input_label": "PDF file",
        "input_name": "pdf",
        "accept": "application/pdf,.pdf",
        "multiple": False,
        "action_label": "Compress PDF",
        "fields": [
            {
            "type": "select",
            "name": "level",
            "label": "Compression level",
            "required": True,
            "value": "medium",
            "options": [
                {"label": "Low (better quality)", "value": "low"},
                {"label": "Medium (balanced)", "value": "medium"},
                {"label": "High (smaller file)", "value": "high"},
            ],
            },
        ],
        "related": ["unlock", "split", "merge", "compress-image"],
        "tips": ["Medium is the best balance.", "High gives more reduction.", "Low preserves quality."],
    },
    {
        "path": "compress-image",
        "title": "Compress Image",
        "icon_html": "🖼️",
        "description": "Reduce image file size while preserving quality.",
        "post_route": "compress_image_route",
        "input_label": "Image file",
        "input_name": "image",
        "accept": "image/*",
        "multiple": False,
        "action_label": "Compress Image",
        "fields": [
            {
            "type": "select",
            "name": "level",
            "label": "Compression level",
            "required": True,
            "value": "medium",
            "options": [
                {"label": "Low (better quality)", "value": "low"},
                {"label": "Medium (balanced)", "value": "medium"},
                {"label": "High (smaller file)", "value": "high"},
            ],
            },
        ],
        "related": ["compress", "images-to-pdf", "pdf-to-images"],
        "tips": ["Use high compression for smaller files.", "Medium keeps a nice balance.", "Supported formats include JPG, PNG, and WEBP."],
        "form_heading": "Upload an image",
        "form_description": "Compress your image file and download the optimized version instantly.",
    },
    {
        "path": "pdf-to-word",
        "title": "PDF to Word",
        "icon_html": "📈",
        "description": "Convert a PDF into an editable Word document.",
        "post_route": "pdf_to_word_route",
        "input_label": "PDF file",
        "input_name": "pdf",
        "accept": "application/pdf,.pdf",
        "multiple": False,
        "action_label": "Convert to Word",
        "fields": [],
        "related": ["office-to-pdf", "pdf-to-excel", "pdf-to-powerpoint"],
        "tips": ["Use a file with clear text.", "The converted file will download automatically.", "Formatting is preserved where possible."],
    },
    {
        "path": "pdf-to-powerpoint",
        "title": "PDF to PowerPoint",
        "icon_html": "📊",
        "description": "Convert PDF pages into PowerPoint slides.",
        "post_route": "pdf_to_powerpoint_route",
        "input_label": "PDF file",
        "input_name": "pdf",
        "accept": "application/pdf,.pdf",
        "multiple": False,
        "action_label": "Convert to PowerPoint",
        "fields": [],
        "related": ["pdf-to-word", "office-to-pdf", "pdf-to-excel"],
        "tips": ["One page becomes one slide.", "Best for simple layouts.", "Large files may take a moment."],
    },
    {
        "path": "pdf-to-excel",
        "title": "PDF to Excel",
        "icon_html": "📊",
        "description": "Extract tables from a PDF into an Excel workbook.",
        "post_route": "pdf_to_excel_route",
        "input_label": "PDF file",
        "input_name": "pdf",
        "accept": "application/pdf,.pdf",
        "multiple": False,
        "action_label": "📊 Convert to Excel",
        "fields": [],
        "related": ["pdf-to-word", "office-to-pdf", "compress"],
        "tips": ["Table-heavy PDFs work best.", "Review the workbook after export.", "Small tables convert cleanest."],
    },
    {
        "path": "office-to-pdf",
        "title": "Office to PDF",
        "icon_html": "📄",
        "description": "Convert Word, Excel or PowerPoint documents into PDF.",
        "post_route": "office_to_pdf_route",
        "input_label": "Document file",
        "input_name": "document",
        "accept": ".docx,.doc,.xlsx,.xls,.pptx,.ppt",
        "multiple": False,
        "action_label": "Convert to PDF",
        "fields": [],
        "related": ["pdf-to-word", "pdf-to-powerpoint", "pdf-to-excel"],
        "tips": ["Use supported Office file formats.", "The PDF downloads automatically.", "Large presentations may take a few moments."],
    },
    {
        "path": "qr-code",
        "title": "Generate QR Code",
        "icon_html": "🔲",
        "description": "Create a QR code from a website URL and download it as a PNG.",
        "post_route": "qr_code_route",
        "has_file": False,
        "fields": [
            {"type": "url", "name": "url", "label": "Website URL", "placeholder": "https://example.com", "required": True},
        ],
        "action_label": "Generate QR Code",
        "related": ["office-to-pdf", "pdf-to-word", "compress"],
        "tips": ["Include the full URL so the QR code scans correctly.", "Use HTTPS links for best compatibility.", "Download the PNG and share it anywhere."],
        "form_heading": "Generate a QR code",
        "form_description": "Enter the website URL to create a downloadable QR code image.",
    },
    {
        "path": "pdf-to-images",
        "title": "PDF to Images",
        "icon_html": "🖼️",
        "description": "Convert PDF pages into JPG images and download as a ZIP.",
        "post_route": "pdf_to_images_route",
        "input_label": "PDF file",
        "input_name": "pdf",
        "accept": "application/pdf,.pdf",
        "multiple": False,
        "action_label": "Convert to Images",
        "fields": [
            {"type": "number", "name": "dpi", "label": "DPI (72–300)", "placeholder": "150", "required": True, "value": "150", "min": "72", "max": "300"},
        ],
        "related": ["images-to-pdf", "compress", "compress-image", "pdf-to-word"],
        "tips": ["150 DPI is a good balance.", "High DPI produces larger images.", "Perfect for image previews."],
    },
    {
        "path": "images-to-pdf",
        "title": "Images to PDF",
        "icon_html": "📷",
        "description": "Combine multiple images into a single PDF file.",
        "post_route": "images_to_pdf_route",
        "input_label": "Image files",
        "input_name": "images",
        "accept": "image/*",
        "multiple": True,
        "action_label": "Create PDF",
        "fields": [],
        "related": ["pdf-to-images", "office-to-pdf", "merge", "compress-image"],
        "tips": ["Upload JPG, PNG, GIF, or BMP files.", "Files are combined in selected order.", "Use images with consistent orientation."],
    },
    {
        "path": "rotate",
        "title": "Rotate PDF",
        "icon_html": "🔄",
        "description": "Rotate selected PDF pages by 90, 180, or 270 degrees.",
        "post_route": "rotate_pdf",
        "input_label": "PDF file",
        "input_name": "pdf",
        "accept": "application/pdf,.pdf",
        "multiple": False,
        "action_label": "Rotate PDF",
        "fields": [
            {"type": "text", "name": "page_ranges", "label": "Pages to rotate (optional)", "placeholder": "Example: 1-3,5", "required": False},
            {
            "type": "select",
            "name": "angle",
            "label": "Angle",
            "required": True,
            "value": "90",
            "options": [
                {"label": "90°", "value": "90"},
                {"label": "180°", "value": "180"},
                {"label": "270°", "value": "270"},
            ],
            },
        ],
        "related": ["split", "delete-pages", "compress"],
        "tips": ["Choose 90 or 270 for portrait changes.", "Leave pages blank to rotate the whole document.", "Rotate before compressing for best results."],
    },
    {
        "path": "delete-pages",
        "title": "Delete Pages",
        "icon_html": "🗑️",
        "description": "Remove unwanted pages from your PDF in one step.",
        "post_route": "delete_pdf_pages_route",
        "input_label": "PDF file",
        "input_name": "pdf",
        "accept": "application/pdf,.pdf",
        "multiple": False,
        "action_label": "Delete Pages",
        "fields": [
            {"type": "text", "name": "page_ranges", "label": "Pages to remove", "placeholder": "Example: 1-3,5", "required": True},
        ],
        "related": ["split", "merge", "compress"],
        "tips": ["Use commas and dashes for ranges.", "Double-check page numbers before submitting.", "The updated PDF downloads automatically."],
    },
]



TOOLS_BY_PATH = {tool["path"]: tool for tool in TOOLS}
TOOL_PATHS = {tool["path"] for tool in TOOLS}
TOOL_BY_POST_PATH = {
    "unlock": "unlock",
    "lock": "lock",
    "split": "split",
    "merge": "merge",
    "compress": "compress",
    "compress-image": "compress-image",
    "pdf-to-images": "pdf-to-images",
    "images-to-pdf": "images-to-pdf",
    "pdf-to-word": "pdf-to-word",
    "pdf-to-powerpoint": "pdf-to-powerpoint",
    "pdf-to-excel": "pdf-to-excel",
    "office-to-pdf": "office-to-pdf",
    "qr-code": "qr-code",
    "rotate-pdf": "rotate",
    "delete-pdf-pages": "delete-pages",
}
